const TodosTypes = {
    GET_TODO_LIST: 'GET_TODO_LIST',
    GET_TODO_LIST_RESPONSE: 'GET_TODO_LIST_RESPONSE',

    ADD_TODOS: 'ADD_TODOS',
    ADD_TODOS_RESPONSE: 'ADD_TODOS_RESPONSE',

    UPDATE_TODOS: 'UPDATE_TODOS',
    UPDATE_TODOS_RESPONSE: 'UPDATE_TODOS_RESPONSE',
    
    DELETE_TODOS: 'DELETE_TODOS',
    DELETE_TODOS_RESPONSE: 'DELETE_TODOS_RESPONSE'
}

export default TodosTypes;